# Generated by Django 5.1.15 on 2026-09-25 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('apelido', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(max_length=10)),
                ('tipo_documento', models.CharField(default='Bilhete de Identidade', max_length=100)),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('nuit', models.CharField(blank=True, max_length=50, null=True)),
                ('nacionalidade', models.CharField(default='Moçambicana', max_length=100)),
                ('provincia', models.CharField(default='Maputo', max_length=100)),
                ('distrito', models.CharField(default='Cidade de Maputo', max_length=100)),
                ('pai', models.CharField(blank=True, max_length=255, null=True)),
                ('mae', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('contato_responsavel', models.CharField(blank=True, max_length=50, null=True)),
                ('email_responsavel', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(default='ATIVO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='tenants.escola')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'sige_alunos',
            },
        ),
    ]
