# Generated by Django 5.1.15 on 2026-09-25 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='turmas.turma'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['escola'], name='sige_alunos_escola__17189b_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['turma'], name='sige_alunos_turma_i_27b792_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['matricula'], name='sige_alunos_matricu_4736ae_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['status'], name='sige_alunos_status_0db47b_idx'),
        ),
    ]
