# Generated by Django 5.1.15 on 2026-09-25 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pauta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ano_letivo', models.CharField(default='2026', max_length=10)),
                ('periodo', models.CharField(max_length=20)),
                ('status', models.CharField(default='ABERTA', max_length=20)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('homologado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pautas', to='tenants.escola')),
            ],
            options={
                'verbose_name': 'Pauta',
                'verbose_name_plural': 'Pautas',
                'db_table': 'sige_pautas',
            },
        ),
    ]
