# Generated by Django 5.1.15 on 2026-09-25 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pautas', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauta',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pautas', to='turmas.turma'),
        ),
        migrations.AddIndex(
            model_name='pauta',
            index=models.Index(fields=['escola'], name='sige_pautas_escola__1f6181_idx'),
        ),
        migrations.AddIndex(
            model_name='pauta',
            index=models.Index(fields=['turma'], name='sige_pautas_turma_i_a7ec7f_idx'),
        ),
        migrations.AddIndex(
            model_name='pauta',
            index=models.Index(fields=['periodo'], name='sige_pautas_periodo_a1172c_idx'),
        ),
        migrations.AddIndex(
            model_name='pauta',
            index=models.Index(fields=['status'], name='sige_pautas_status_a218d7_idx'),
        ),
    ]
