# Generated by Django 5.1.15 on 2026-09-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0002_initial'),
        ('tenants', '0002_alter_assinaturaescola_valor_and_more'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pauta',
            constraint=models.UniqueConstraint(fields=('escola', 'turma', 'ano_letivo', 'periodo'), name='unique_pauta_turma_ano_periodo'),
        ),
    ]
