# Generated by Django 5.1.15 on 2026-09-25 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('disciplinas', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoEdicaoNotas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=20)),
                ('autorizado_por', models.CharField(max_length=255)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sige_permissoes_edicao_notas',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=20)),
                ('teste1', models.FloatField(blank=True, default=0, null=True)),
                ('teste2', models.FloatField(blank=True, default=0, null=True)),
                ('teste3', models.FloatField(blank=True, null=True)),
                ('teste4', models.FloatField(blank=True, null=True)),
                ('trabalho', models.FloatField(blank=True, default=0, null=True)),
                ('avaliacao_trimestral', models.FloatField(blank=True, default=0, null=True)),
                ('media_final', models.FloatField(default=0)),
                ('faltas', models.IntegerField(default=0)),
                ('anotacao', models.CharField(blank=True, max_length=10, null=True)),
                ('comportamento', models.CharField(default='S', max_length=5)),
                ('resultado', models.CharField(default='Aprovado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='alunos.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='disciplinas.disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='tenants.escola')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'sige_notas',
            },
        ),
    ]
