# Generated by Django 5.1.15 on 2026-09-25 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0001_initial'),
        ('notas', '0001_initial'),
        ('professores', '0001_initial'),
        ('tenants', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='turmas.turma'),
        ),
        migrations.AddField(
            model_name='permissaoedicaonotas',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_edicao', to='disciplinas.disciplina'),
        ),
        migrations.AddField(
            model_name='permissaoedicaonotas',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_edicao', to='tenants.escola'),
        ),
        migrations.AddField(
            model_name='permissaoedicaonotas',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_edicao', to='professores.professor'),
        ),
        migrations.AddField(
            model_name='permissaoedicaonotas',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_edicao', to='turmas.turma'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['escola'], name='sige_notas_escola__04153a_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['aluno'], name='sige_notas_aluno_i_deb9c5_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['disciplina'], name='sige_notas_discipl_8ddcb1_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['turma'], name='sige_notas_turma_i_7f2ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['periodo'], name='sige_notas_periodo_f201e7_idx'),
        ),
        migrations.AddIndex(
            model_name='permissaoedicaonotas',
            index=models.Index(fields=['escola'], name='sige_permis_escola__4bc68b_idx'),
        ),
        migrations.AddIndex(
            model_name='permissaoedicaonotas',
            index=models.Index(fields=['professor'], name='sige_permis_profess_43b1f6_idx'),
        ),
        migrations.AddIndex(
            model_name='permissaoedicaonotas',
            index=models.Index(fields=['ativa'], name='sige_permis_ativa_66b716_idx'),
        ),
    ]
