# Generated by Django 5.1.15 on 2026-09-25 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_initial'),
        ('disciplinas', '0002_alter_disciplina_carga_horaria_and_more'),
        ('notas', '0002_initial'),
        ('tenants', '0002_alter_assinaturaescola_valor_and_more'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='avaliacao_trimestral',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='faltas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='media_final',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='teste1',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='teste2',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='teste3',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='teste4',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='trabalho',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('escola', 'aluno', 'disciplina', 'turma', 'periodo'), name='unique_nota_aluno_disciplina_periodo'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.CheckConstraint(condition=models.Q(('media_final__gte', 0.0), ('media_final__lte', 20.0)), name='check_nota_media_final_range'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.CheckConstraint(condition=models.Q(('faltas__gte', 0)), name='check_nota_faltas_positivas'),
        ),
    ]
