services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sige_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://sige_user:sige_secure_pass_2026@postgres:5432/sige_db?schema=public
      - JWT_SECRET=sige_super_secret_jwt_key_enterprise_2026_xpto!
      - JWT_REFRESH_SECRET=sige_super_secret_refresh_token_enterprise_2026!
      - APP_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sige_network

  postgres:
    image: postgres:16-alpine
    container_name: sige_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sige_user
      POSTGRES_PASSWORD: sige_secure_pass_2026
      POSTGRES_DB: sige_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sige_user -d sige_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sige_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sige_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sige.com
      PGADMIN_DEFAULT_PASSWORD: sige_admin_pass
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - sige_network

volumes:
  postgres_data:
    driver: local

networks:
  sige_network:
    driver: bridge
