services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sige_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - SECRET_KEY=sige_django_super_secret_enterprise_2026_mz!
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgresql://sige_user:sige_secure_pass_2026@postgres:5432/sige_db
      - POSTGRES_DB=sige_db
      - POSTGRES_USER=sige_user
      - POSTGRES_PASSWORD=sige_secure_pass_2026
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,http://localhost:80,http://localhost
      - JWT_SECRET_KEY=sige_super_secret_jwt_key_enterprise_2026_xpto!
      - JWT_ACCESS_LIFETIME_MINUTES=120
      - JWT_REFRESH_LIFETIME_DAYS=7
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sige_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sige_frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - sige_network

  postgres:
    image: postgres:16-alpine
    container_name: sige_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sige_user
      POSTGRES_PASSWORD: sige_secure_pass_2026
      POSTGRES_DB: sige_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sige_user -d sige_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sige_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sige_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sige.com
      PGADMIN_DEFAULT_PASSWORD: sige_admin_pass
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - sige_network

volumes:
  postgres_data:
    driver: local

networks:
  sige_network:
    driver: bridge
