# Generated by Django 5.1.15 on 2026-09-25 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialEscolar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classe', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nome_arquivo', models.CharField(default='material.pdf', max_length=255)),
                ('extensao', models.CharField(default='pdf', max_length=20)),
                ('tamanho_bytes', models.BigIntegerField(default=0)),
                ('conteudo_base64', models.TextField(blank=True, null=True)),
                ('tipo_mime', models.CharField(default='application/pdf', max_length=100)),
                ('arquivo_url', models.URLField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual Escolar'), ('FICHA', 'Ficha de Exercícios'), ('LIVRO', 'Livro Didático'), ('EXERCICIOS', 'Caderno de Exercícios'), ('GUIA', 'Guia do Professor'), ('OUTRO', 'Outro Recurso')], default='MANUAL', max_length=50)),
                ('publicado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='disciplinas.disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_escolares', to='tenants.escola')),
            ],
            options={
                'verbose_name': 'Material Escolar',
                'verbose_name_plural': 'Materiais Escolares',
                'db_table': 'sige_material_escolar',
                'indexes': [models.Index(fields=['escola'], name='sige_materi_escola__a7acbe_idx'), models.Index(fields=['classe'], name='sige_materi_classe_46c0a2_idx'), models.Index(fields=['tipo'], name='sige_materi_tipo_0066ca_idx')],
            },
        ),
    ]
