# Generated by Django 5.1.15 on 2026-09-25 09:43

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Administrador do SaaS'), ('ADMIN_ESCOLA', 'Administrador da Escola'), ('DIRECTOR_ESCOLA', 'Director de Escola'), ('DAP', 'Director Adjunto Pedagógico (DAP)'), ('CHEFE_SECRETARIA', 'Chefe de Secretaria'), ('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno'), ('FINANCEIRO', 'Financeiro')], default='ADMIN_ESCOLA', max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('aluno_id', models.UUIDField(blank=True, null=True)),
                ('professor_id', models.UUIDField(blank=True, null=True)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='tenants.escola')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'sige_usuarios',
            },
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.CharField(default='127.0.0.1', max_length=50)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_acesso', to='tenants.escola')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sige_logs_acesso',
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['escola'], name='sige_usuari_escola__b66ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['role'], name='sige_usuari_role_58fcc6_idx'),
        ),
        migrations.AddIndex(
            model_name='logacesso',
            index=models.Index(fields=['escola'], name='sige_logs_a_escola__62f378_idx'),
        ),
        migrations.AddIndex(
            model_name='logacesso',
            index=models.Index(fields=['tipo'], name='sige_logs_a_tipo_f45c40_idx'),
        ),
        migrations.AddIndex(
            model_name='logacesso',
            index=models.Index(fields=['created_at'], name='sige_logs_a_created_ec6620_idx'),
        ),
    ]
