# Generated by Django 5.1.15 on 2026-09-25 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50)),
                ('classe', models.CharField(default='10ª Classe', max_length=50)),
                ('area', models.CharField(default='Geral', max_length=50)),
                ('carga_horaria', models.IntegerField(default=60)),
                ('ano_letivo', models.CharField(default='2026', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='tenants.escola')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'db_table': 'sige_disciplinas',
                'indexes': [models.Index(fields=['escola'], name='sige_discip_escola__6f9fb1_idx'), models.Index(fields=['codigo'], name='sige_discip_codigo_0b5867_idx')],
            },
        ),
    ]
