# Generated by Django 5.1.15 on 2026-09-25 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
        ('tenants', '0002_alter_assinaturaescola_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='disciplina',
            constraint=models.UniqueConstraint(fields=('escola', 'codigo', 'ano_letivo'), name='unique_disciplina_escola_codigo_ano_letivo'),
        ),
    ]
