# Generated by Django 5.1.15 on 2026-09-25 09:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duracao_dias', models.IntegerField(default=30)),
                ('max_alunos', models.IntegerField(default=500)),
                ('max_professores', models.IntegerField(default=50)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'db_table': 'sige_planos',
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('nif_cnpj', models.CharField(max_length=50, unique=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='ATIVA', max_length=20)),
                ('ano_letivo_ativo', models.CharField(default='2026', max_length=10)),
                ('trimestre_ativo', models.CharField(default='1_TRIMESTRE', max_length=20)),
                ('data_adesao', models.DateTimeField(default=django.utils.timezone.now)),
                ('provincia', models.CharField(default='Maputo', max_length=100)),
                ('distrito', models.CharField(default='Cidade de Maputo', max_length=100)),
                ('director_nome', models.CharField(default='Prof. Dr. António Costa', max_length=255)),
                ('director_carreira', models.CharField(default='Professor Doutor', max_length=100)),
                ('dap_nome', models.CharField(default='Prof. João Baptista', max_length=255)),
                ('chefe_secretaria_nome', models.CharField(default='Dra. Maria Eunice', max_length=255)),
                ('usar_emblema_nacional', models.BooleanField(default=True)),
                ('codigo_escola', models.CharField(blank=True, max_length=50, null=True)),
                ('logo_base64', models.TextField(blank=True, null=True)),
                ('bloqueada_manualmente', models.BooleanField(default=False)),
                ('permitir_visualizacao_notas', models.BooleanField(default=True)),
                ('inscricoes_abertas', models.BooleanField(default=False)),
                ('inscricoes_inicio', models.DateTimeField(blank=True, null=True)),
                ('inscricoes_fim', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escolas', to='tenants.plano')),
            ],
            options={
                'verbose_name': 'Escola (Tenant)',
                'verbose_name_plural': 'Escolas (Tenants)',
                'db_table': 'sige_escolas',
            },
        ),
        migrations.CreateModel(
            name='AssinaturaEscola',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='ATIVA', max_length=20)),
                ('metodo_pagamento', models.CharField(default='TRANSFERENCIA', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='tenants.escola')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='tenants.plano')),
            ],
            options={
                'db_table': 'sige_assinaturas_escolas',
            },
        ),
        migrations.AddIndex(
            model_name='escola',
            index=models.Index(fields=['status'], name='sige_escola_status_5929db_idx'),
        ),
        migrations.AddIndex(
            model_name='escola',
            index=models.Index(fields=['email'], name='sige_escola_email_b0a5be_idx'),
        ),
        migrations.AddIndex(
            model_name='assinaturaescola',
            index=models.Index(fields=['escola'], name='sige_assina_escola__7137ae_idx'),
        ),
        migrations.AddIndex(
            model_name='assinaturaescola',
            index=models.Index(fields=['status'], name='sige_assina_status_4d0fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='assinaturaescola',
            index=models.Index(fields=['data_fim'], name='sige_assina_data_fi_57cc6f_idx'),
        ),
    ]
