# Generated by Django 5.1.15 on 2026-09-25 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinaturaescola',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plano',
            name='duracao_dias',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='plano',
            name='max_alunos',
            field=models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='plano',
            name='max_professores',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='plano',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='assinaturaescola',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__gte', models.F('data_inicio'))), name='check_assinatura_datas_coerentes'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaescola',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='check_assinatura_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='plano',
            constraint=models.CheckConstraint(condition=models.Q(('preco__gte', 0)), name='check_plano_preco_positivo'),
        ),
        migrations.AddConstraint(
            model_name='plano',
            constraint=models.CheckConstraint(condition=models.Q(('max_alunos__gte', 1)), name='check_plano_max_alunos_positivo'),
        ),
        migrations.AddConstraint(
            model_name='plano',
            constraint=models.CheckConstraint(condition=models.Q(('max_professores__gte', 1)), name='check_plano_max_professores_positivo'),
        ),
    ]
