# Generated by Django 5.1.15 on 2026-09-25 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('mes_referencia', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('data_vencimento', models.DateTimeField()),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('recibo_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='alunos.aluno')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='tenants.escola')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'sige_pagamentos',
                'indexes': [models.Index(fields=['escola'], name='sige_pagame_escola__e3e421_idx'), models.Index(fields=['aluno'], name='sige_pagame_aluno_i_8cc30a_idx'), models.Index(fields=['status'], name='sige_pagame_status_1a8c7b_idx'), models.Index(fields=['mes_referencia'], name='sige_pagame_mes_ref_62ae3c_idx')],
            },
        ),
    ]
