# Generated by Django 5.1.15 on 2026-09-25 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_initial'),
        ('pagamentos', '0001_initial'),
        ('tenants', '0002_alter_assinaturaescola_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='check_pagamento_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_pago__gte', 0)), name='check_pagamento_valor_pago_positivo'),
        ),
    ]
