# Generated by Django 5.1.15 on 2026-09-25 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('codigo_autenticidade', models.CharField(max_length=100, unique=True)),
                ('qrcode_data', models.TextField()),
                ('emitido_em', models.DateTimeField(auto_now_add=True)),
                ('emitido_por', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='alunos.aluno')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='tenants.escola')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'db_table': 'sige_certificados',
                'indexes': [models.Index(fields=['escola'], name='sige_certif_escola__1ee0d7_idx'), models.Index(fields=['aluno'], name='sige_certif_aluno_i_6097f7_idx'), models.Index(fields=['codigo_autenticidade'], name='sige_certif_codigo__95236e_idx')],
            },
        ),
    ]
