# Generated by Django 5.1.15 on 2026-09-25 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogImpressao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('conteudo_json', models.TextField(blank=True, null=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sige_logs_impressao',
            },
        ),
        migrations.CreateModel(
            name='DocumentoSalvo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('ano_letivo', models.CharField(default='2026', max_length=10)),
                ('dados_json', models.TextField()),
                ('hash_md5', models.CharField(blank=True, max_length=64, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_salvos', to='alunos.aluno')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_salvos', to='tenants.escola')),
            ],
            options={
                'db_table': 'sige_documentos_salvos',
            },
        ),
    ]
