# Generated by Django 5.1.15 on 2026-09-25 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('tenants', '0001_initial'),
        ('turmas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosalvo',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_salvos', to='turmas.turma'),
        ),
        migrations.AddField(
            model_name='documentosalvo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_salvos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logimpressao',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_impressao', to='tenants.escola'),
        ),
        migrations.AddField(
            model_name='logimpressao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_impressao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentosalvo',
            index=models.Index(fields=['escola'], name='sige_docume_escola__b35c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosalvo',
            index=models.Index(fields=['tipo_documento'], name='sige_docume_tipo_do_4dcad1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosalvo',
            index=models.Index(fields=['aluno'], name='sige_docume_aluno_i_18c8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosalvo',
            index=models.Index(fields=['turma'], name='sige_docume_turma_i_37480f_idx'),
        ),
        migrations.AddIndex(
            model_name='logimpressao',
            index=models.Index(fields=['escola'], name='sige_logs_i_escola__e66710_idx'),
        ),
        migrations.AddIndex(
            model_name='logimpressao',
            index=models.Index(fields=['tipo_documento'], name='sige_logs_i_tipo_do_798624_idx'),
        ),
        migrations.AddIndex(
            model_name='logimpressao',
            index=models.Index(fields=['data_emissao'], name='sige_logs_i_data_em_7b5e91_idx'),
        ),
    ]
