# Generated by Django 5.1.15 on 2026-09-25 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('apelido', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(default='M', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_documento', models.CharField(default='Bilhete de Identidade', max_length=100)),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('nuit', models.CharField(blank=True, max_length=50, null=True)),
                ('nacionalidade', models.CharField(default='Moçambicana', max_length=100)),
                ('provincia', models.CharField(default='Maputo', max_length=100)),
                ('distrito', models.CharField(default='Cidade de Maputo', max_length=100)),
                ('carreira', models.CharField(default='DN1', max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('carga_horaria_semanal', models.IntegerField(default=20)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'db_table': 'sige_professores',
            },
        ),
        migrations.CreateModel(
            name='AlocacaoDocente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='disciplinas.disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='tenants.escola')),
            ],
            options={
                'verbose_name': 'Alocação Docente',
                'verbose_name_plural': 'Alocações Docentes',
                'db_table': 'sige_professor_disciplina_turma',
            },
        ),
    ]
