# Generated by Django 5.1.15 on 2026-09-25 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0001_initial'),
        ('tenants', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaodocente',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='turmas.turma'),
        ),
        migrations.AddField(
            model_name='professor',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='tenants.escola'),
        ),
        migrations.AddField(
            model_name='alocacaodocente',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='professores.professor'),
        ),
        migrations.AddIndex(
            model_name='professor',
            index=models.Index(fields=['escola'], name='sige_profes_escola__897f61_idx'),
        ),
        migrations.AddIndex(
            model_name='professor',
            index=models.Index(fields=['email'], name='sige_profes_email_7466a7_idx'),
        ),
        migrations.AddIndex(
            model_name='alocacaodocente',
            index=models.Index(fields=['escola'], name='sige_profes_escola__e7cd08_idx'),
        ),
        migrations.AddIndex(
            model_name='alocacaodocente',
            index=models.Index(fields=['professor'], name='sige_profes_profess_1cc5ca_idx'),
        ),
        migrations.AddIndex(
            model_name='alocacaodocente',
            index=models.Index(fields=['disciplina'], name='sige_profes_discipl_0186ee_idx'),
        ),
        migrations.AddIndex(
            model_name='alocacaodocente',
            index=models.Index(fields=['turma'], name='sige_profes_turma_i_ed8f41_idx'),
        ),
    ]
