# Generated by Django 5.1.15 on 2026-09-25 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_alter_disciplina_carga_horaria_and_more'),
        ('professores', '0002_initial'),
        ('tenants', '0002_alter_assinaturaescola_valor_and_more'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='carga_horaria_semanal',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='alocacaodocente',
            constraint=models.UniqueConstraint(fields=('escola', 'professor', 'disciplina', 'turma'), name='unique_alocacao_docente_disciplina_turma'),
        ),
    ]
