# Generated by Django 5.1.15 on 2026-09-25 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('grau_ano', models.CharField(max_length=50)),
                ('turno', models.CharField(default='MANHA', max_length=20)),
                ('sala', models.CharField(blank=True, max_length=50, null=True)),
                ('ano_letivo', models.CharField(default='2026', max_length=10)),
                ('area', models.CharField(default='Geral', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('director_classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_como_director_classe', to='professores.professor')),
                ('director_turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_como_director_turma', to='professores.professor')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='tenants.escola')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'sige_turmas',
                'indexes': [models.Index(fields=['escola'], name='sige_turmas_escola__34f919_idx'), models.Index(fields=['ano_letivo'], name='sige_turmas_ano_let_3c3b1c_idx'), models.Index(fields=['grau_ano'], name='sige_turmas_grau_an_c99dae_idx')],
            },
        ),
    ]
