# Generated by Django 5.1.15 on 2026-09-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0003_alter_professor_carga_horaria_semanal_and_more'),
        ('tenants', '0002_alter_assinaturaescola_valor_and_more'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('escola', 'nome', 'ano_letivo'), name='unique_turma_escola_nome_ano_letivo'),
        ),
    ]
